/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invou.Views;

import invou.PrintLabel;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import javax.swing.JOptionPane;
/**
 *
 * @author leoas
 */
public class View extends javax.swing.JFrame {
    /**
     * Creates new form pruebaa
     */
    public View() {
        initComponents();
        this.setLocationRelativeTo(null);
        jToolBar2.setFloatable(false);
    }

    
    
    public void addModifyEquipment(SearchEquipment se, String Id_equipment)
    {
        ModifyEquipment equipment = new ModifyEquipment(this, se, Id_equipment);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }
    
    public void addSearchEquipment(ModifyEquipment me)
    {
        SearchEquipment equipment = new SearchEquipment(me);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }
    
    public void addSearchEquipment(IngressEquipmentRepair ier)
    {
        SearchEquipment equipment = new SearchEquipment(ier);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        ButtonEnviarAReparacion = new javax.swing.JButton();
        ButtonRegresoDeReparacion = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        tonnerMenu = new javax.swing.JMenu();
        addTonner = new javax.swing.JMenuItem();
        deleteTonner = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        listTonner = new javax.swing.JMenu();
        entryList = new javax.swing.JMenuItem();
        exitList = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        StockList = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        registryTonner = new javax.swing.JMenuItem();
        updateStock = new javax.swing.JMenuItem();
        printerMenu = new javax.swing.JMenu();
        enviarImpresoraAReparacion = new javax.swing.JMenuItem();
        regresoDeReparacion = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        listPrinter = new javax.swing.JMenu();
        listRepair = new javax.swing.JMenuItem();
        listPrint = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        registrarImpresora = new javax.swing.JMenuItem();
        newPagesPrinted = new javax.swing.JMenuItem();
        monitorMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        ListEquipment = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        registerRepair = new javax.swing.JMenuItem();
        ListRepairEquipment = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        print = new javax.swing.JMenuItem();
        monitorMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        equiposMenu = new javax.swing.JMenu();
        menu_proveedores = new javax.swing.JMenu();
        listarProveedor = new javax.swing.JMenuItem();
        registrarProveedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invou");
        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/tonnerAdd28.png"))); // NOI18N
        jButton3.setToolTipText("Ingreso de tonner");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/tonnerDelete28.png"))); // NOI18N
        jButton4.setToolTipText("Egreso de tonner");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);
        jToolBar2.add(jSeparator3);

        ButtonEnviarAReparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/printerRepair28.png"))); // NOI18N
        ButtonEnviarAReparacion.setToolTipText("Impresora en reparacion");
        ButtonEnviarAReparacion.setAlignmentX(0.5F);
        ButtonEnviarAReparacion.setFocusable(false);
        ButtonEnviarAReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarAReparacionActionPerformed(evt);
            }
        });
        jToolBar2.add(ButtonEnviarAReparacion);

        ButtonRegresoDeReparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/printerOk.png"))); // NOI18N
        ButtonRegresoDeReparacion.setToolTipText("Impresora reparada");
        ButtonRegresoDeReparacion.setAlignmentX(0.5F);
        ButtonRegresoDeReparacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonRegresoDeReparacion.setFocusable(false);
        ButtonRegresoDeReparacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRegresoDeReparacion.setName("gfgbb"); // NOI18N
        ButtonRegresoDeReparacion.setNextFocusableComponent(ButtonEnviarAReparacion);
        ButtonRegresoDeReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresoDeReparacionActionPerformed(evt);
            }
        });
        jToolBar2.add(ButtonRegresoDeReparacion);
        jToolBar2.add(jSeparator4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorDelete.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton6);
        jToolBar2.add(jSeparator5);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        tonnerMenu.setText("Tonner");

        addTonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/tonnerAdd16.png"))); // NOI18N
        addTonner.setText("Ingresar");
        addTonner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTonnerActionPerformed(evt);
            }
        });
        tonnerMenu.add(addTonner);

        deleteTonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/tonnerDelete16.png"))); // NOI18N
        deleteTonner.setText("Retirar ");
        deleteTonner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTonnerActionPerformed(evt);
            }
        });
        tonnerMenu.add(deleteTonner);
        tonnerMenu.add(jSeparator1);

        listTonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/list16.png"))); // NOI18N
        listTonner.setText("Listar");

        entryList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/downArrow16 .png"))); // NOI18N
        entryList.setText("Ingresos");
        entryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryListActionPerformed(evt);
            }
        });
        listTonner.add(entryList);

        exitList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/upArrow16 .png"))); // NOI18N
        exitList.setText("Egresos");
        exitList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitListActionPerformed(evt);
            }
        });
        listTonner.add(exitList);
        listTonner.add(jSeparator2);

        StockList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/stock16.png"))); // NOI18N
        StockList.setText("Stock");
        StockList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockListActionPerformed(evt);
            }
        });
        listTonner.add(StockList);

        tonnerMenu.add(listTonner);
        tonnerMenu.add(jSeparator6);

        registryTonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/registryEditor16.png"))); // NOI18N
        registryTonner.setText("Registrar nuevo código");
        registryTonner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryTonnerActionPerformed(evt);
            }
        });
        tonnerMenu.add(registryTonner);

        updateStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/updateStock16.png"))); // NOI18N
        updateStock.setText("Actualizar stock");
        updateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockActionPerformed(evt);
            }
        });
        tonnerMenu.add(updateStock);

        jMenuBar1.add(tonnerMenu);

        printerMenu.setText("Impresoras");

        enviarImpresoraAReparacion.setText("Enviar a reparacion");
        enviarImpresoraAReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarImpresoraAReparacionActionPerformed(evt);
            }
        });
        printerMenu.add(enviarImpresoraAReparacion);

        regresoDeReparacion.setText("Regreso de reparacion");
        regresoDeReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoDeReparacionActionPerformed(evt);
            }
        });
        printerMenu.add(regresoDeReparacion);
        printerMenu.add(jSeparator8);

        listPrinter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/list16.png"))); // NOI18N
        listPrinter.setText("Listar");

        listRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/downArrow16 .png"))); // NOI18N
        listRepair.setText("Reparaciones");
        listRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRepairActionPerformed(evt);
            }
        });
        listPrinter.add(listRepair);

        listPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/upArrow16 .png"))); // NOI18N
        listPrint.setText("Impresoras");
        listPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPrintActionPerformed(evt);
            }
        });
        listPrinter.add(listPrint);

        printerMenu.add(listPrinter);
        printerMenu.add(jSeparator7);

        registrarImpresora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/registryEditor16.png"))); // NOI18N
        registrarImpresora.setText("Registrar nueva impresora");
        registrarImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarImpresoraActionPerformed(evt);
            }
        });
        printerMenu.add(registrarImpresora);

        newPagesPrinted.setText("Actualizar paginas impresas");
        newPagesPrinted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPagesPrintedActionPerformed(evt);
            }
        });
        printerMenu.add(newPagesPrinted);

        jMenuBar1.add(printerMenu);

        monitorMenu1.setText("Equipos");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        jMenuItem5.setText("Registrar nuevo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        monitorMenu1.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        jMenuItem6.setText("Modificar/Borrar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        monitorMenu1.add(jMenuItem6);

        ListEquipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        ListEquipment.setText("Listar equipamiento");
        ListEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEquipmentActionPerformed(evt);
            }
        });
        monitorMenu1.add(ListEquipment);
        monitorMenu1.add(jSeparator9);

        registerRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        registerRepair.setText("Registrar reparación");
        registerRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerRepairActionPerformed(evt);
            }
        });
        monitorMenu1.add(registerRepair);

        ListRepairEquipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        ListRepairEquipment.setText("Listar Reparaciones");
        ListRepairEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRepairEquipmentActionPerformed(evt);
            }
        });
        monitorMenu1.add(ListRepairEquipment);
        monitorMenu1.add(jSeparator10);

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        print.setText("Imprimir etiqueta");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        monitorMenu1.add(print);

        jMenuBar1.add(monitorMenu1);

        monitorMenu.setText("Monitores");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorAdd16 .png"))); // NOI18N
        jMenuItem4.setText("Ingreso de Monitor");
        monitorMenu.add(jMenuItem4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invou/imagenes/monitorDelete16.png"))); // NOI18N
        jMenuItem3.setText("Egreso de Monitor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        monitorMenu.add(jMenuItem3);

        jMenuBar1.add(monitorMenu);

        equiposMenu.setText("Edit");
        jMenuBar1.add(equiposMenu);

        menu_proveedores.setText("Proveedores");

        listarProveedor.setText("Listar proveedores");
        listarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProveedorActionPerformed(evt);
            }
        });
        menu_proveedores.add(listarProveedor);

        registrarProveedor.setText("Registrar Proveedor");
        registrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProveedorActionPerformed(evt);
            }
        });
        menu_proveedores.add(registrarProveedor);

        jMenuBar1.add(menu_proveedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEnviarAReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarAReparacionActionPerformed
        PrinterRepairNew repair = new PrinterRepairNew();
        jDesktopPane1.add(repair);
        repair.show();
    }//GEN-LAST:event_ButtonEnviarAReparacionActionPerformed

    private void ButtonRegresoDeReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresoDeReparacionActionPerformed
        PrinterRepairReturn repair = new PrinterRepairReturn();
        jDesktopPane1.add(repair);
        repair.show();
    }//GEN-LAST:event_ButtonRegresoDeReparacionActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void addTonnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTonnerActionPerformed
    IngressToner ing = new IngressToner();
    jDesktopPane1.add(ing);
    ing.show();
    }//GEN-LAST:event_addTonnerActionPerformed

    private void deleteTonnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTonnerActionPerformed
    EgressToner egr = new EgressToner();
    jDesktopPane1.add(egr);
    egr.show();
    }//GEN-LAST:event_deleteTonnerActionPerformed

    private void registryTonnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryTonnerActionPerformed
        RegisterNewToner art = new RegisterNewToner();
        jDesktopPane1.add(art);
        art.show(); 
    }//GEN-LAST:event_registryTonnerActionPerformed

    public void addInPanel()
    {
        RegisterNewToner art = new RegisterNewToner();
        jDesktopPane1.add(art);
        art.show(); 
    }
    
    private void StockListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockListActionPerformed
        SearchStockToner bus = new SearchStockToner();
        bus.show();        
    }//GEN-LAST:event_StockListActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EgressToner egr = new EgressToner();
        jDesktopPane1.add(egr);
        egr.show();        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        IngressToner ing = new IngressToner();
        jDesktopPane1.add(ing);
        ing.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockActionPerformed
        InterfazActualizarStock stock = new InterfazActualizarStock();
        jDesktopPane1.add(stock);
        stock.show(); 
    }//GEN-LAST:event_updateStockActionPerformed

    private void entryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryListActionPerformed
        SearchIncomeToner ingresos = new SearchIncomeToner();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = ingresos.getSize();
        ingresos.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(ingresos);
        ingresos.show();
    }//GEN-LAST:event_entryListActionPerformed

    private void exitListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitListActionPerformed
        SearchExitsToner egresos = new SearchExitsToner();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = egresos.getSize();
        egresos.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(egresos);
        egresos.show();
    }//GEN-LAST:event_exitListActionPerformed

    private void listarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProveedorActionPerformed
        InterfazListarProveedores listaProv = new InterfazListarProveedores();
        jDesktopPane1.add(listaProv);
        listaProv.show();
    }//GEN-LAST:event_listarProveedorActionPerformed

    private void registrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProveedorActionPerformed
        RegisterNewProvider prov = new RegisterNewProvider();
        jDesktopPane1.add(prov);
        prov.show();
    }//GEN-LAST:event_registrarProveedorActionPerformed

    private void registrarImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarImpresoraActionPerformed
        RegisterNewPrint impresora = new RegisterNewPrint();
        jDesktopPane1.add(impresora);
        impresora.show();
    }//GEN-LAST:event_registrarImpresoraActionPerformed

    private void listRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRepairActionPerformed
        SearchPrinterRepair repairs = new SearchPrinterRepair();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = repairs.getSize();
        repairs.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(repairs);
        repairs.show();
    }//GEN-LAST:event_listRepairActionPerformed

    private void listPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPrintActionPerformed
        SearchPrinter printers = new SearchPrinter();
        printers.show();
    }//GEN-LAST:event_listPrintActionPerformed

    private void enviarImpresoraAReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarImpresoraAReparacionActionPerformed
        PrinterRepairNew repair = new PrinterRepairNew();
        jDesktopPane1.add(repair);
        repair.show();
    }//GEN-LAST:event_enviarImpresoraAReparacionActionPerformed

    private void regresoDeReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoDeReparacionActionPerformed
        PrinterRepairReturn repair = new PrinterRepairReturn();
        jDesktopPane1.add(repair);
        repair.show();
    }//GEN-LAST:event_regresoDeReparacionActionPerformed

    private void newPagesPrintedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPagesPrintedActionPerformed
        UpdatePagesPrinted pages = new UpdatePagesPrinted();
        jDesktopPane1.add(pages);
        pages.show();        
    }//GEN-LAST:event_newPagesPrintedActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        RegisterNewEquipment equipment = new RegisterNewEquipment(this);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void ListEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEquipmentActionPerformed
        SearchEquipment equipment = new SearchEquipment(this);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }//GEN-LAST:event_ListEquipmentActionPerformed

    private void registerRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerRepairActionPerformed
        IngressEquipmentRepair equipment = new IngressEquipmentRepair(this);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }//GEN-LAST:event_registerRepairActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        
        SearchEquipment equipment = new SearchEquipment();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }//GEN-LAST:event_printActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ModifyEquipment equipment = new ModifyEquipment(this);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void ListRepairEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRepairEquipmentActionPerformed
        SearchEquipmentRepair equipment = new SearchEquipmentRepair();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = equipment.getSize();
        equipment.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(equipment);
        equipment.show();
    }//GEN-LAST:event_ListRepairEquipmentActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new View().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEnviarAReparacion;
    private javax.swing.JButton ButtonRegresoDeReparacion;
    private javax.swing.JMenuItem ListEquipment;
    private javax.swing.JMenuItem ListRepairEquipment;
    private javax.swing.JMenuItem StockList;
    private javax.swing.JMenuItem addTonner;
    private javax.swing.JMenuItem deleteTonner;
    private javax.swing.JMenuItem entryList;
    private javax.swing.JMenuItem enviarImpresoraAReparacion;
    private javax.swing.JMenu equiposMenu;
    private javax.swing.JMenuItem exitList;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem listPrint;
    private javax.swing.JMenu listPrinter;
    private javax.swing.JMenuItem listRepair;
    private javax.swing.JMenu listTonner;
    private javax.swing.JMenuItem listarProveedor;
    private javax.swing.JMenu menu_proveedores;
    private javax.swing.JMenu monitorMenu;
    private javax.swing.JMenu monitorMenu1;
    private javax.swing.JMenuItem newPagesPrinted;
    private javax.swing.JMenuItem print;
    private javax.swing.JMenu printerMenu;
    private javax.swing.JMenuItem registerRepair;
    private javax.swing.JMenuItem registrarImpresora;
    private javax.swing.JMenuItem registrarProveedor;
    private javax.swing.JMenuItem registryTonner;
    private javax.swing.JMenuItem regresoDeReparacion;
    private javax.swing.JMenu tonnerMenu;
    private javax.swing.JMenuItem updateStock;
    // End of variables declaration//GEN-END:variables
}
